- README.md
Fixed it by compiling all the generator file together without the file name
Also made the output name explicit (for some reason the built file was getting named as 'classmodels' without the -o flag)
> README was referencing a missing file generator.go.

- .travis.yml
- README.md
Currently this change only does build of all the code. We need to add 'go test' too into travis script.
For some reason i was getting weird errors when doing go test -v ./...
> Add travis support for googlapis/openapis-compiler

- plugins/swift/openapi_swift_generator/Package.swift
Resolves [this issue](https://github.com/googleapis/openapi-compiler/issues/26).
> Update Stencil to an official tagged version [Swift]

- OpenAPIv3/schema-generator/main.go
Prohibit additional properties in schema definitions, otherwise, the JSON schema is too permissive. 
OpenAPI v3 specification provides [specification extensions](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#specificationExtensions) to define additional (custom) properties.
A too permissive schema can also cause false negatives (false validation errors) on a valid OpenAPI v3 specification. Let's take this example, it's simplified version of [PetStore](https://github.com/OAI/OpenAPI-Specification/pull/985/files#diff-4530232d2a5e2e4be11ab57cd8ba8894):
```yaml
openapi: "3.0.0"
info:
version: 1.0.0
title: Swagger Petstore
license:
name: MIT
paths: {}
components:
schemas:
Pet:
properties:
name:
type: string
Pets:
type: array
items:
$ref: …
```
> Prohibit additional properties in schema definitions

- OpenAPIv3/openapi-3.0.json
- OpenAPIv3/schema-generator/main.go
[Based on the openapi-v3.0.0-rc2 branch]
Generated JSON Schema uses the following values as regex in patternProperties:
* `{name}`
* `{path}`
* `{media-type}`
* `{expression}`
* `{property}`
They are human-friendly and easy to understand, but unfortunately, JSON Schema validator does not treat it the same way as humans. 
[In JSON Schema](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.17):
> Each property name of this ("patternProperties") object SHOULD be a valid regular expression, according to the ECMA 262 regular expression dialect.  
ECMA 262 does not allow using `{` and `}` as a PatternCharacters:
> PatternCharacter ::
SourceCharacter but not one of -
^ $ \ . * + ? ( ) [ ] { } |
and treats their combination as a …
> Fix regex in patternProperties

- OpenAPIv3/openapi-3.0.json
- OpenAPIv3/schema-generator/main.go
As the `header` object takes its structure from the `parameter` object, we must copy the `patternProperties` as well as the `properties`, i.e. we make it extendable with specification extensions.
Similar disclaimer to before; go novice.
> Copy patternProperties from parameter to header object

- OpenAPIv2/OpenAPIv2.go
- OpenAPIv3/OpenAPIv3.go
- compiler/helpers.go
- generate-gnostic/generate-compiler.go
- generate-gnostic/generate-extension.go
- generate-gnostic/main.go
The majority of uses of regex inside of the generated code suffer from easy to fix problems:
1. Use of uncompiled patterns - there are no patterns that aren't known ahead of time
2. Use of regex for trivial string operations.
This PR fixes kubernetes/kubernetes#49776 by removing the impact of the two issues above at
generation time.
In production systems using the generated code (Kubernetes and OpenShift) we measured that 1/3rd of all startup allocations and the majority of startup time was being consumed by this code (which is being used to parse and display OpenAPI models).  After this fix, allocations from this package drop to effectively zero.
> Reduce the amount of memory and CPU used by generated by OpenAPI code

- .gitignore
1. Adds IntelliJ project files to .gitignore. It is usefull for new Goglang IDE.
2. Ignores generated files of the extension sample. If we run 'make' it creates a folder 'extensions/sample/generated' with generated files. It should not be tracked by git.
> Ignore generated extension files and IntelliJ IDEA project files

- README.md
Paths to OpenAPI examples are incorrect.
> Fix wrong file paths in documentation

- OpenAPIv3/schema-generator/main.go
See https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#contact-object
> The email address of the contact person/organization. MUST be in the format of an email address.
Added a `"format": "email"`. Similar approach is used in [JSON Schema for Swagger v2](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/schemas/v2.0/schema.json#L142)
> The URL pointing to the contact information. MUST be in the format of a URL.
JSON Schema Draft 4 does not have a string format for URL (see [Proposal: add format "url"](https://github.com/json-schema-org/json-schema-spec/issues/233)). The best approximation is `"format": "uri"` which is also used in JSON Schema for [Swagger v2](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/schemas/v2.0/schema.json#L …
> JSON Schema for OAS3: Validate Contact#url and Contact#email

- plugins/gnostic-go-generator/render_client.go
There is a bug in gnostic-go-generator plugin. If request method is POST and body has not parameters it throws the error: 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1268347]
How to reproduce:
`gnostic --go-client-out=outdir examples/v2.0/json/petstore.json`
>  Fix null pointer exception if POST method has not body params

- plugins/environment.go
If we try to run a plugin as standalone program it will print the error and stops the execution. It happens because the model is not initialized.
How to reproduce:
Generate protocol buffer binary file with gnostic from any OpenAPI(Swagger) file and run gnostic-go-generator plugin from command line.
Also an attempt to deserialize OpenAPIv3 should not be done as independent. It may set incorrect value to the 'err' variable and return unexpected error.
> Initialize request surface if a plugin runs as standalone program

- .travis.yml
- plugins/gnostic-go-generator/examples/v2.0/sample/Makefile
- plugins/gnostic-go-generator/examples/v2.0/sample/README.md
- plugins/gnostic-go-generator/examples/v2.0/sample/sample.yaml
- plugins/gnostic-go-generator/examples/v2.0/sample/sample_test.go
- plugins/gnostic-go-generator/examples/v2.0/sample/service/app.yaml
- plugins/gnostic-go-generator/examples/v2.0/sample/service/init.go
- plugins/gnostic-go-generator/examples/v2.0/sample/service/main.go
- plugins/gnostic-go-generator/examples/v2.0/sample/service/service.go
- plugins/gnostic-go-generator/language.go
- plugins/gnostic-go-generator/render_types.go
This commit addresses these issues:
https://github.com/googleapis/gnostic/issues/74
https://github.com/googleapis/gnostic/issues/73
Disclaimer: gnostic-go-generator is a demo plugin;
many OpenAPI features remain unsupported.
> gnostic-go-generator improvements

- .gitignore
- linters/node/gnostic-lint-responses/Makefile
- linters/node/gnostic-lint-responses/README.md
- linters/node/gnostic-lint-responses/gnostic-lint-responses.js
- linters/node/gnostic-lint-responses/package.json
This PR adds a Node-based linter to check operation responses and flag any that are top-level arrays.
> Add linter plugin to check for array responses

- plugins/gnostic-go-generator/examples/v2.0/apis_guru/main.go
- plugins/gnostic-go-generator/examples/v2.0/bookstore/bookstore/bookstore.go
- plugins/gnostic-go-generator/examples/v2.0/sample/sample/sample.go
- plugins/gnostic-go-generator/examples/v2.0/xkcd/main.go
- plugins/gnostic-go-generator/examples/v2.0/xkcd/xkcd/xkcd.go
- plugins/gnostic-go-generator/examples/v3.0/bookstore/bookstore/bookstore.go
- plugins/gnostic-go-generator/examples/v3.0/urlshortener/urlshortener/urlshortener.go
Trying to recursively `go get` gnostic was failing, e.g.:
```go get -v -d github.com/googleapis/gnostic/plugins/...```
because these example Go files assume you have followed along with
the READMEs (or run the Makefile) and generated the libs the
examples depend on.
First I tried using `// +build ignore` signals to `go get` and `go build` that
they shouldn't evaluate these files, which did fix `go get` but broke
anything that tried to actually build these files (e.g. makefiles) and
broke the build.
Instead I have added placeholder packages for all of the packages that
will be generated but are not present, which allows `go get` to succeed,
e.g.:
```
googleapis$ go get -d -v ./gnostic/...
```
Fixes #87
> Add imported generated packages so that `go get` with `...` can succeed

- OpenAPIv2/OpenAPIv2.go
- OpenAPIv3/OpenAPIv3.go
- examples/v2.0/yaml/empty-v2.yaml
- examples/v3.0/yaml/empty-v3.yaml
- generate-gnostic/generate-compiler.go
- generate-gnostic/types.go
- gnostic_test.go
- printer/code.go
- surface/model_openapiv2.go
- surface/model_openapiv3.go
- test/v2.0/json/empty-v2.json
- test/v3.0/json/empty-v3.json
Prior to this change, required fields would be omitted if they
were set to their default values.
Reported in GitHub Issue #82.
> Modify generated ToRawInfo methods to always include required fields.

- .travis-install.sh
- Makefile
- gnostic.go
* `goimports` wasn't explicitly installed by root `make build`, but is exec'd by `gnostic-go-generator` plugin (it is installed by the plugin's target).
* plugins were failing silently because `plugins.HandleResponse` return value (the potential plugin error) was being ignored
> fix silent plugin failures & goimports dep

- .travis-install.sh
- .travis.yml
* removes `.travis-install.sh`
* removes gnostic-swift-generator install/tests from Travis
Decided in #95 conversation
> remove install & tests for swift

- compiler/reader.go
- compiler/reader_test.go
- compiler/testdata/petstore.yaml
fixed for #99
- when cache is disabled, the result should not be added into cache
- add full unit test for the 4 apis
> improvement for cache apis

- apps/report/main.go
This fixes a panic reported in https://github.com/googleapis/gnostic/issues/98.
Underlying this, the apps/report sample is only written to support OpenAPIv2. It was crashing when given OpenAPIv3 input. We should probably also update apps/report to work with OpenAPIv3.
> Update apps/report sample to report better errors for non-OpenAPIv2 input.

- plugins/gnostic-go-generator/examples/v2.0/bookstore/Makefile
- plugins/gnostic-go-generator/examples/v2.0/sample/Makefile
- plugins/gnostic-go-generator/examples/v3.0/bookstore/Makefile
- plugins/gnostic-go-generator/main.go
I wanted to be able to run -output . or -output /path/to/dir
Using format.Source was the easiest way I could figure out how to
validate the package name.
Relates to #111
> Resolve package name from output path

- surface/model_openapiv3.go
- Surface model now includes types from components/Parameters, components/RequestBodies and components/Responses sections from the OpenAPI spec
- Surface model now includes types that use the reference object ($ref) inside of OpenAPI spec for parameters, request bodies, responses
> Enhancements for the surface model

- surface/model_openapiv3.go
- surface/type.go
Given following OpenAPI description: 
paths:
/testParameterReference:
get:
operationId: testParameterReference
parameters:
- $ref: '#/components/parameters/Parameter1'
responses:
200:
description: success    
components:
parameters:
Parameter1:
name: param1
in: query
schema:
type: integer
format: int64
The surface model creates a field with following properties:
Notice the Position property of the field that defaults to Position_BODY which is not correct.
This PR sets the Position of the field to the referenced parameters position (in this case Position_QUERY).
An alternative solution would be to use a pointer for the 'Position' property and let it default to nil instead of Position_BODY.
Additionally, I am not sure about the [switch …
> Adding the position of a reference field.

- gnostic.go
- plugins/environment.go
- surface/model.go
- surface/model_openapiv2.go
- surface/model_openapiv3.go
A recursive implementation for the surface model for v2. The implementation is very similar to the one for v3. I moved functions and structs, that are used by both versions, to the model.go file.
> Improved version of surface model for v2

- surface/model_openapiv2.go
- surface/model_openapiv3.go
During surface-building, we were logging messages about empty response bodies which suggested these were problems. In some situations (e.g. deletes), this can be a desired behavior, so we remove the messages.
> Remove messages about responses with no contents.

- plugins/README.md
- plugins/environment.go
- plugins/gnostic-plugin-request/main.go
- plugins/gnostic-process-plugin-response/main.go
This adds two standalone helper utilities:
- `gnostic-plugin-request`, a plugin that captures a plugin request and writes it in .json and binary .pb form. When the new optional -verbose flag is provided, this plugin logs the request to stdout.
- `gnostic-process-plugin-response`, a standalone tool that reads a plugin response on stdin and handles the response in the same way that `gnostic` does. 
These tools make it easier to test plugins standalone.
First, this writes the plugin request to local files `plugin-request.json` and `plugin-request.pb`
`% gnostic myapi.json --plugin-request-out=.` 
Then a plugin can be run standalone:
`% gnostic-go-generator --plugin < plugin-request.pb > plugin-response.pb`
Then use the following to process the plugin response:
`% …
> Add plugin development helpers and verbose flag for plugins.

- compiler/reader.go
While writing a couple of tools that mass-process API specs in parallel goroutines, I found some synchronization problems caused by the shared caches used in the reader. This PR protects all of the public functions in compiler/reader.go with mutexes for the file and info caches.
> Synchronize accesses to reader cache maps.

- surface/model_openapiv3.go
- This PR creates better types and fields in case a schema has sub schemas which are defined with OneOf, AnyOf, or AllOf relation. The first commit fixes [issue 22](https://github.com/googleapis/gnostic-grpc/issues/22) in gnostic-grpc.
For example `input.yaml`:
```
components:
schemas:
Pet:
type: object
required:
- pet_type
properties:
pet_type:
type: string
discriminator:
propertyName: pet_type
Dog:     # "Dog" is a value for the pet_type property (the discriminator value)
allOf: # Combines the main `Pet` schema with `Dog`-specific properties
- $ref: '#/components/schemas/Pet'
- type: object
properties:
bark:
type: boolean
breed:
type: string
enum: [Dingo, Husky, Retriever, Shepherd]
```
gnostic-grpc would now generate:
```
message Pet {
string pet_type = 1;
}
message Dog {
Pet pet = 1; …
```
> Handle OneOf, AnyOf, and AllOf sub schemas

- surface/model_openapiv3.go
Produces correct surface field in case we are dealing with arrays.
Sorry for second PR.
> Add support for enum arrays

- apps/vocabulary/main.go
- apps/vocabulary/v2Processor.go
- apps/vocabulary/v3Processor.go
This pull request builds upon my previous one by including functionality for v3 APIs. The structure now for the vocabulary app is as follows: main.go receives an API description, determines which API version it received and then calls one of the two following files: v2Processor.go or v3Processor.go. Both files follow the same flow but are specific to the structure of that API's version.
> Vocabulary App for V2 and V3

- Makefile
Some tests run separately-built binaries, and when the sources for these change, the tests don't always get rerun (due to the [Go test cache](https://stackoverflow.com/questions/48882691/force-retesting-or-disable-test-caching)). To fix this, this PR adds a `go clean -testcache` at the beginning of `make test`.
> clear the testcache in "make test"

- compiler/helpers.go
Tests in gnostic-grpc are currently failing due to [PR194](https://github.com/googleapis/gnostic/pull/194).
Currently, `ResponseOrRefernce` is not properly constructed, because gnostic does [not recognize](https://github.com/googleapis/gnostic/blob/ce2874882b96283118ceb88bf3b651e37636963e/openapiv3/OpenAPIv3.go#L3726) that a yaml node can also have the tag "!!int".
This PR fixes all test cases in gnostic-grpc.
> Adding an additional case for ScalarNodes with tag "!!int".

- compiler/helpers.go
- discovery/discovery.go
- generate-gnostic/generate-compiler.go
- openapiv2/OpenAPIv2.go
- openapiv3/OpenAPIv3.go
This fixes crashes in the yaml.v3 export functions that were discovered for newly-added specs in public directories.
> ToRawInfo functions return null-valued nodes instead of nil

- README.md
Fixed build badge. The org name was `googleapis` instead of `google` in the build badge
fixes #224
> fixed build status badge

- apps/protoc-gen-openapi/examples/tests/mapfields/message.proto
- apps/protoc-gen-openapi/examples/tests/mapfields/openapi.yaml
- apps/protoc-gen-openapi/generator/openapi-v3.go
- apps/protoc-gen-openapi/plugin_test.go
As illustrated in the new test, this change causes map fields of the form:
```
map<string, string> labels = 2;
```
to be represented as "objects" in OpenAPI.
```
labels:
type: object
```
This change was made to correctly generate https://github.com/apigee/registry/blob/main/openapi.yaml
> Update protoc-gen-openapi to represent map<string,string> as OpenAPI objects.

- apps/protoc-gen-openapi/generator/openapi-v3.go
The `extension` variable is an interface and was only checked for `nil`, but not whether `xt.Zero()` would be assigned to the interface.
This leads to a crash, if a method within a service was not annotated.
Closes #248
> Fixed incorrect interface nil check in protoc-gen-openapi

- apps/protoc-gen-openapi/examples/tests/mapfields/message.proto
- apps/protoc-gen-openapi/examples/tests/mapfields/openapi.yaml
- apps/protoc-gen-openapi/examples/tests/mapfields/openapi_json.yaml
- apps/protoc-gen-openapi/generator/openapi-v3.go
This ensures proper conversion of maps and lists of standard types, (some) google.protobuf types and sub messages.
> protoc-gen-openapi: Convert maps and lists of sub messages

- apps/protoc-gen-openapi/examples/google/example/library/v1/openapi.yaml
- apps/protoc-gen-openapi/examples/google/example/library/v1/openapi_json.yaml
- apps/protoc-gen-openapi/examples/tests/bodymapping/openapi.yaml
- apps/protoc-gen-openapi/examples/tests/bodymapping/openapi_json.yaml
- apps/protoc-gen-openapi/examples/tests/jsonoptions/openapi.yaml
- apps/protoc-gen-openapi/examples/tests/jsonoptions/openapi_json.yaml
- apps/protoc-gen-openapi/examples/tests/mapfields/openapi.yaml
- apps/protoc-gen-openapi/examples/tests/mapfields/openapi_json.yaml
- apps/protoc-gen-openapi/examples/tests/noannotations/openapi.yaml
- apps/protoc-gen-openapi/examples/tests/noannotations/openapi_json.yaml
- apps/protoc-gen-openapi/examples/tests/pathparams/openapi.yaml
- apps/protoc-gen-openapi/examples/tests/pathparams/openapi_json.yaml
- apps/protoc-gen-openapi/examples/tests/protobuftypes/openapi.yaml
- apps/protoc-gen-openapi/examples/tests/protobuftypes/openapi_json.yaml
- apps/protoc-gen-openapi/generator/openapi-v3.go
All schemas defined in "components" will now have "type" set to "object".
> protoc-gen-openapi: Add type to schema objects

- go.mod
Remove any knowledge of multi modules from pkg.go.dev, etc.
> Retract v0.6.0

- cmd/disco/go.mod
- cmd/parse-linter-output/go.mod
- cmd/petstore-builder/go.mod
- cmd/protoc-gen-jsonschema/go.mod
- cmd/protoc-gen-openapi/go.mod
- cmd/report-messages/go.mod
- cmd/report/go.mod
- cmd/vocabulary-operations/go.mod
This commit should be tagged as v0.6.3
> Retract breaking multi-module commit

- cmd/protoc-gen-openapi/examples/tests/protobuftypes/message.proto
- cmd/protoc-gen-openapi/examples/tests/protobuftypes/openapi.yaml
- cmd/protoc-gen-openapi/examples/tests/protobuftypes/openapi_json.yaml
- cmd/protoc-gen-openapi/generator/openapi-v3.go
- third_party/google/api/httpbody.proto
google.api.HttpBody is another special case, that is handled explicitly by Envoy.
The behavior has been tested with Envoy.
GET requests with google.api.HttpBody as request param, will actually read POST data and pass it along.
This can not allowed in OpenAPI though.
In OpenAPI, the response is defined as Content Type */*.
> protoc-gen-openapi: Handle google.api.HttpBody

- cmd/protoc-gen-jsonschema/generator/json-schema.go
- cmd/protoc-gen-jsonschema/main.go
- cmd/protoc-gen-jsonschema/plugin_test.go
- cmd/protoc-gen-openapi/examples/tests/enumoptions/message.proto
- cmd/protoc-gen-openapi/examples/tests/enumoptions/openapi.yaml
- cmd/protoc-gen-openapi/examples/tests/enumoptions/openapi_string_enum.yaml
- cmd/protoc-gen-openapi/generator/openapi-v3.go
- cmd/protoc-gen-openapi/main.go
- cmd/protoc-gen-openapi/plugin_test.go
This change exposes a configuration option that enables Protobuf enums to be compiled to enums with the underlying type of `string`.
The following Protobuf message:
```protobuf
message Message {
Kind kind = 1;
}
enum Kind {
KIND_UNSPECIFIED = 0;
KIND_1 = 1;
KIND_2 = 2;
}
```
Will be compiled to the following OpenAPI spec:
```yaml
Message:
type: object
properties:
kind:
format: enum
type: string
enum:
- KIND_UNSPECIFIED
- KIND_1
- KIND_2
```
And will be compiled to the following jsonschema spec:
```json
{
"title": "Message",
"$id": "http://example.com/schemas/Message.json",
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "object",
"properties": {
"kind": {
"title": "kind",
"type": "string",
"enum": [
"KIND_UNSPECIFIED",
"KIND_1",
"KIND_2"
],
"format": "enum"
}
}
}
```
To …
> protoc-gen-openapi/jsonschema: Add support for string-based enums

- cmd/protoc-gen-openapi/generator/generator.go
- cmd/protoc-gen-openapi/generator/reflector.go
- cmd/protoc-gen-openapi/generator/utils.go
- cmd/protoc-gen-openapi/generator/wellknown/mediatypes.go
- cmd/protoc-gen-openapi/generator/wellknown/schemas.go
- cmd/protoc-gen-openapi/main.go
First, this is based off of my previous PR #327 so this PR shows some of the changes in that PR too. If you want to see just the changes in this PR you can look at this compare here:
https://github.com/jeffsawatzky/gnostic/compare/grpc-status...jeffsawatzky:refactoring
- the code in the protoc-gen-openapi project was all in one file and it was hard for me to locate stuff. I tried moving the code around a bit to separate it a little and hopefully make it a bit easier to digest.
1) Most of the schemas and media types for well known things were moved to a `wellknown` files
2) The code that takes `protoreflect` descriptors and returns schemas based on those descriptors was moved into a `reflector` file
3) All the remaining code that operates on the `protogen` classes stayed in the `generator` …
> [protoc-gen-openapi] Refactoring some code around

- generate-gnostic/generate-compiler.go
- openapiv2/OpenAPIv2.go
- openapiv3/OpenAPIv3.go
Fixes #322. Thanks @jeffsawatzky for catching this weirdness!
> Add missing generated code to support export of maps of strings.

- openapiv3/annotations.proto
We are currently using `1042` for the extension number, which is currently ["registered"](https://github.com/protocolbuffers/protobuf/blob/main/docs/options.md) for protoc-gen-openapiv2 from the grpc-gateway project. I have created a PR to create a new registered extension number for gnostic [here](https://github.com/protocolbuffers/protobuf/pull/9754/files).
And this PR updates the extension number gnostic uses to the one registered in that PR.
@timburks not sure if you have any "pull" over in the protobuf repo to get that PR approved and merged?
> [openapiv3 annotations.proto] Use a Registered Extension Number

- COMPILE-PROTOS.sh
- openapiv3/README.md
This fixes the extra files when running `make` or `COMPILE-PROTOS.sh` as mentioned in #348.
> Fix COMPILE_PROTOS.sh

- .github/workflows/go.yml
[This](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/) could explain why CI is failing (since April?).
> Update action to use ubuntu-22.04

- metrics/vocabulary/vocabulary.go
This ensures that a check of `err` happens before a deferred `Close()`.
> metrics/vocabulary: err check before Close()

- plugins/gnostic-analyze/summarize/main.go
This picks up an `err` variable that was being passed into a walker function and then ignored.
> plugins/gnostic-analyze/summarize: fix dropped error

- cmd/protoc-gen-openapi/README.md
Fix this error in the installation instructions:
```
go install github.com/google/gnostic/cmd/protoc-gen-openapi
go: 'go install' requires a version when current directory is not in a module
Try 'go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest' to install the latest version
```
> chore: Update README.md to fix installation instructions
