- OpenAPIv3/openapi-3.0.json
- OpenAPIv3/schema-generator/main.go
refs #42 
Please forgive me, these are the first lines of go I've ever written and I haven't done any reading on the language. Happy to rev the PR.
> Amend Scopes and HTTP Response Code regexes

- plugins/gnostic-lint/README.md
- plugins/gnostic-swift-sample/Makefile
A few little changes to smooth over some bumps I encountered in my first attempt to build/use the linter.
> Minor updates to linter

- plugins/environment.go
https://github.com/googleapis/gnostic/issues/85
> Fix bad error check in plugins/environments.go

- README.md
> Updating README: step 8 using plugins

- plugins/gnostic-go-generator/language.go
- plugins/gnostic-go-generator/render_client.go
- plugins/gnostic-go-generator/render_server.go
- surface/model_openapiv3.go
Fixing a couple of problems with my api (#110). I can work on adding tests if you want to point me in the right direction.
> Fix some edge cases

- compiler/reader.go
Body should always be closed even if status code is not 200
> fix(resp): fix connection leak problem of missing response body close

- apps/disco/openapiv3.go
> added nil pointer check for disco/openapiv3

- plugins/gnostic-go-generator/renderer.go
> added error handling to golang plugin renderer

- README.md
Reported in https://github.com/googleapis/gnostic/issues/118
> Fix incorrect URL in README.

- .travis.yml
- Makefile
- apps/disco/main.go
- compiler/reader.go
- compiler/reader_test.go
- generate-gnostic/generate-extension_test.go
- generate-gnostic/test/errors/x-extension-name-collision.errors
- go.mod
- go.sum
Tests in compiler and generate-gnostic were broken. This fixes them and adds them to CI testing.
> Update Makefile to run all tests (and fixed broken tests).

- gnostic.go
- lib/gnostic.go
Fixes https://github.com/googleapis/gnostic/issues/159.
This was broken by the refactoring in https://github.com/googleapis/gnostic/pull/153.
> Display usage information on errors and when the --help option is given.

- lib/gnostic.go
> Fix crash found by fuzzing.

- gnostic_test.go
- lib/gnostic.go
- testdata/discovery/discovery-v1.text
The gnostic command-line reader for Discovery docs was broken by the yaml.v3 change. This fixes it.  
TODO before merging: add a test to gnostic_test.go.
> Fix error in discovery reader.

- lib/gnostic.go
Fix checking of error from jsonwriter.Marshal.
> Fix checking of error from jsonwriter.Marshal

- jsonwriter/README.md
- jsonwriter/writer.go
- jsonwriter/writer_test.go
Support JSON marshalling of yaml sequence and scalar nodes.
> Support JSON marshalling of yaml sequence and scalar nodes

- apps/protoc-gen-openapi/examples/google/example/library/v1/openapi.yaml
- apps/protoc-gen-openapi/generator/openapi-v3.go
minor fix to remove a log message from the plugin
> Minor fixes to protoc-gen-openapi: remove extraneous log message, update openapi version in generated files

- apps/protoc-gen-openapi/examples/google/example/library/v1/openapi.yaml
- apps/protoc-gen-openapi/generator/openapi-v3.go
This adds appropriate handling of google.protobuf.Empty and google.api.HttpBody.
These changes were used to generate https://github.com/apigee/registry/pull/141
> Improve protoc-gen-openapi generation of response bodies.

- apps/protoc-gen-jsonschema/examples/tests/embedded/message.proto
- apps/protoc-gen-jsonschema/examples/tests/embedded/schemas_json/Message.json
- apps/protoc-gen-jsonschema/examples/tests/embedded/schemas_proto/Message.json
- apps/protoc-gen-jsonschema/examples/tests/embedded/testdata_json/Message.json
- apps/protoc-gen-jsonschema/examples/tests/mapfields/schemas_json/Message.json
- apps/protoc-gen-jsonschema/examples/tests/mapfields/schemas_proto/Message.json
- apps/protoc-gen-jsonschema/generator/json-schema.go
- apps/protoc-gen-jsonschema/plugin_test.go
- go.mod
- go.sum
This fixes an issue with protoc-gen-jsonschema.
When embedded messages had embedded messages, the definitions would not be set on the "root" message.
> Fix embedded messages

- cmd/disco/go.mod
- cmd/parse-linter-output/go.mod
- cmd/petstore-builder/go.mod
- cmd/protoc-gen-jsonschema/go.mod
- cmd/protoc-gen-openapi/go.mod
- cmd/report-messages/go.mod
- cmd/report/go.mod
- cmd/vocabulary-operations/go.mod
- go.mod
This should be tagged as v0.6.5
> Retract sub modules again

- cmd/disco/go.mod
- cmd/parse-linter-output/go.mod
- cmd/petstore-builder/go.mod
- cmd/protoc-gen-jsonschema/go.mod
- cmd/protoc-gen-openapi/go.mod
- cmd/report-messages/go.mod
- cmd/report/go.mod
- cmd/vocabulary-operations/go.mod
- go.mod
> Remove multi module again

- cmd/protoc-gen-openapi/examples/tests/protobuftypes/message.proto
- cmd/protoc-gen-openapi/examples/tests/protobuftypes/openapi.yaml
- cmd/protoc-gen-openapi/examples/tests/protobuftypes/openapi_json.yaml
- cmd/protoc-gen-openapi/generator/openapi-v3.go
gRPC transcoding handles google.protobuf.Value as a catch all value.
> Handle google.protobuf.Value

- lib/gnostic.go
Found and suggested by @hojongs in #287
> Add missing check in gnostic validateOptions().

- cmd/protoc-gen-openapi/examples/tests/additional_bindings/message.proto
- cmd/protoc-gen-openapi/examples/tests/additional_bindings/openapi.yaml
- cmd/protoc-gen-openapi/generator/generator.go
- cmd/protoc-gen-openapi/plugin_test.go
fix: https://github.com/google/gnostic/issues/345
> feat: support generate doc with additional_bindings

- .github/workflows/go.yml
Tests stopped running on PRs when the main branch became "main".
> Update CI to run on "main" branch.
